# Generated by Django 4.0.4 on 2022-06-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.IntegerField(verbose_name='性别')),
                ('activate', models.BooleanField(verbose_name='是否活跃')),
                ('description', models.CharField(max_length=255, verbose_name='描述')),
            ],
        ),
    ]
