# Generated by Django 4.0.4 on 2022-06-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SerializerDemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='activate',
            field=models.BooleanField(default=True, verbose_name='是否活跃'),
        ),
        migrations.AlterField(
            model_name='student',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='描述'),
        ),
    ]
