# Generated by Django 4.0.4 on 2022-06-09 23:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SerializerDemo', '0004_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='加入时间'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='加入时间'),
        ),
    ]
